sudo: required

services:
  - docker

before_install:
  - docker-compose build 

script:
  - docker-compose run tests

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t jfernandes/e2e-tests .; 
    docker login --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD";
    docker push jfernandes/e2e-tests;
    fi
